# see https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Short Intro: index.md
  - Steganography: what-is-stego.md
  - Planning: planning-out-system.md
  - Encoding: encoding.md
  - Decoding: decoding.md

################################################################################

# displayed in the tab bar and as the page title
site_name: Space Steganography Tutorial

# base URL where docs will be hosted. by making it a subdir of the real site, we help that out.
site_url: https://almendra.dev/project/eng240-stego/tutorial

# set colorscheme options
theme: 
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo

# material markdown extensions
markdown_extensions:
  # pretty boxes like "note" "warning" "error"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
