# see https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Welcome!: index.md
  - Steganography: what-is-steg.md
  - Planning: planning-design.md
  - Encoding: encoding.md
  - Decoding: decoding.md

################################################################################

# set dir for content to `tutorial`
docs_dir: tutorial

# displayed in the tab bar and as the page title
site_name: Space Steganography Tutorial

# base URL where docs will be hosted. by making it a subdir of the real site, we help that out.
site_url: https://almendra.dev/project/eng240-steg/tutorial

theme: 
  name: material
  features:
    # allow code copying with easy button.
    - content.code.copy
  icon:
    # make the annotation icon a ?
    annotation: material/help-circle
  palette:
    # set colorscheme to a good one
    scheme: slate
    primary: black
    accent: indigo

# markdown extensions (I use a bunch of them)
markdown_extensions:
  # pretty boxes like "note" "warning" "error"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # footnotes for citations
  - footnotes

  # data tables
  - tables

  # group tabs to allow switching between two subpages
  - pymdownx.tabbed:
      alternate_style: true

  # table of contents in each section
  - toc:
      permalink: true
      title: In this section

  # attribute lists let me make file downloads
  - attr_list

# load additional CSS code
extra_css:
  - stylesheets/extra.css
